import { notFound } from "next/navigation";
import Link from "next/link";
import { NoteSummaryView } from "@/components/note-summary-view";
import { adminDb } from "@/lib/insforge/server";
import type { Note } from "@/lib/insforge/types";
import type { MeetingSummary } from "@/lib/ai/summarize";

export const dynamic = "force-dynamic";

export default async function PublicSharePage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const note = await adminDb.first<Note>("notes", {
    select: ["title", "summary", "created_at"],
    eq: { share_token: token },
  });
  if (!note) notFound();

  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <Link href="/" className="text-sm font-bold tracking-tight">
        MeetNote AI
      </Link>
      <div className="mt-8 rounded-xl border border-zinc-200 bg-white p-8">
        <h1 className="text-2xl font-bold">{note.title}</h1>
        <div className="mt-1 text-xs text-zinc-500">
          {new Date(note.created_at).toLocaleString("en-US")}
        </div>
        {note.summary != null ? (
          <div className="mt-6">
            <NoteSummaryView summary={note.summary as MeetingSummary} />
          </div>
        ) : (
          <p className="mt-6 text-sm text-zinc-500">Summary not generated yet.</p>
        )}
      </div>
      <div className="mt-6 text-center text-xs text-zinc-500">
        Generated by{" "}
        <Link href="/" className="underline">
          MeetNote AI
        </Link>{" "}
        · Want this for yourself?{" "}
        <Link href="/sign-up" className="underline">
          Create a free account
        </Link>
      </div>
    </main>
  );
}
